image: python:3.6.5
pipelines:
  default:
    - step:
        script:
          - python3 -m pip install -r requirements.txt
          - python3 -m pip install pytest
          - python3 setup.py build_ext -i
          - python3 -m pytest -v beancount
