image: atlassian/default-image:2 
pipelines:
  default:
    - step:
        script:
          - apt-get -y install python3
          - apt-get -y install python3-pip
          - python3 -m pip install -r requirements.txt
          - python3 -m pip install nose
          - python3 setup.py build_ext -i
          - nosetests -v beancount
